"""Initial revision

Revision ID: 827139f7a3ef
Revises: 
Create Date: 2023-07-27 14:28:03.132184

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '827139f7a3ef'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('animes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('trailer_link', sa.String(), nullable=False),
    sa.Column('num_episodes', sa.Integer(), nullable=False),
    sa.Column('synopsis', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('episodes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('anime_id', sa.Integer(), nullable=True),
    sa.Column('episode_title', sa.String(), nullable=False),
    sa.Column('episode_link', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['anime_id'], ['animes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_episodes_episode_title'), 'episodes', ['episode_title'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_episodes_episode_title'), table_name='episodes')
    op.drop_table('episodes')
    op.drop_table('animes')
    # ### end Alembic commands ###
