"""Initial revision

Revision ID: a8b0a4984903
Revises: 
Create Date: 2023-07-27 14:28:03.132184

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a8b0a4984903'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('animes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('japanese_title', sa.String(), nullable=False),
    sa.Column('trailer_link', sa.String(), nullable=False),
    sa.Column('num_episodes', sa.Integer(), nullable=False),
    sa.Column('synopsis', sa.String(), nullable=False),
    sa.Column('country', sa.String(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('genres', sa.String(), nullable=False),
    sa.Column('rating', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('studio', sa.String(), nullable=False),
    sa.Column('MPAA', sa.String(), nullable=False),
    sa.Column('duration', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('episodes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('anime_id', sa.Integer(), nullable=True),
    sa.Column('episode_title', sa.String(), nullable=False),
    sa.Column('episode_link', sa.String(), nullable=False),
    sa.Column('translations', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['anime_id'], ['animes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('images',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('big_img', sa.String(), nullable=False),
    sa.Column('small_img', sa.String(), nullable=False),
    sa.Column('screens', sa.JSON(), nullable=False),
    sa.Column('anime_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['anime_id'], ['animes.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('anime_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('images')
    op.drop_table('episodes')
    op.drop_table('animes')
    # ### end Alembic commands ###
