"""Initial revision

Revision ID: a8b0a4984903
Revises: 
Create Date: 2023-07-27 14:28:03.132184

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a8b0a4984903'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'titles',
        sa.Column('id', sa.String(), nullable=False),
        sa.Column('name', sa.String(), nullable=False, unique=True),
        sa.Column('japanese_title', sa.String(), nullable=False),
        sa.Column('trailer_link', sa.String(), nullable=False),
        sa.Column('num_episodes', sa.Integer(), nullable=False),
        sa.Column('synopsis', sa.String(), nullable=False),
        sa.Column('country', sa.String(), nullable=False),
        sa.Column('year', sa.Integer(), nullable=False),
        sa.Column('genres', sa.JSON(), nullable=False),
        sa.Column('rating', sa.String(), nullable=False),
        sa.Column('type', sa.String(), nullable=False),
        sa.Column('status', sa.String(), nullable=False),
        sa.Column('studio', sa.String(), nullable=False),
        sa.Column('MPAA', sa.String(), nullable=False),
        sa.Column('duration', sa.String(), nullable=False),
        sa.Column('screens', sa.JSON(), nullable=False),
        sa.Column('big_img', sa.String(), nullable=False),
        sa.Column('small_img', sa.String(), nullable=False),
        sa.PrimaryKeyConstraint('id')
    )
    
    op.create_table(
        'episodes',
        sa.Column('episode_number', sa.Integer(), nullable=False),
        sa.Column('title_id', sa.String(), sa.ForeignKey('titles.id', ondelete='CASCADE'), nullable=False),
        sa.Column('episode_title', sa.String(), nullable=False),
        sa.Column('episode_link', sa.String(), nullable=False, unique=True),
        sa.Column('translations', sa.JSON(), nullable=False),
        sa.PrimaryKeyConstraint('episode_link'),
        sa.ForeignKeyConstraint(['title_id'], ['titles.id']),
    )
    
    op.create_table(
        'roles',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(), nullable=False),
        sa.Column('is_active_subscription', sa.Boolean(), nullable=False, server_default=sa.text('false')),
        sa.Column('permissions', sa.JSON(), nullable=False, server_default='{}'),
        sa.PrimaryKeyConstraint('id')
    )

    op.create_table(
        'users',
        sa.Column('id', sa.String(), nullable=False),
        sa.Column('user_set_id', sa.String(), nullable=True),
        sa.Column('email', sa.String(), nullable=False),
        sa.Column('username', sa.String(), nullable=False),
        sa.Column('hashed_password', sa.String(), nullable=False),
        sa.Column('role_id', sa.Integer(), sa.ForeignKey('roles.id')),
        sa.Column('is_active', sa.Boolean(), nullable=False, server_default=sa.text('true')),
        sa.Column('is_superuser', sa.Boolean(), nullable=False, server_default=sa.text('false')),
        sa.Column('is_verified', sa.Boolean(), nullable=False, server_default=sa.text('false')),
        sa.PrimaryKeyConstraint('id'),
        sa.ForeignKeyConstraint(['role_id'], ['roles.id']),
    )

    op.create_table(
        'refresh_tokens',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('refresh_token', sa.String(), nullable=False),
        sa.Column('expires_at', sa.Integer(), nullable=True),
        sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.func.now(), nullable=False),
        sa.Column('user_id', sa.String(), sa.ForeignKey('users.id', ondelete='CASCADE'), nullable=False),
        sa.PrimaryKeyConstraint('id'),
    )
    
    op.create_table(
        'messages',
        sa.Column('user_id', sa.String(), primary_key=True),
        sa.Column('chat_id', sa.Integer(), unique=True),
        sa.Column('message', sa.String(), nullable=False)
    )


    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('episodes')
    op.drop_table('titles')
    op.drop_table('refresh_tokens')
    op.drop_table('users')
    op.drop_table('roles')
    op.drop_table('messages')
    # ### end Alembic commands ###
